name: 'Generate Release Notes'
description: 'Generate release notes for Momentum projects (auto-detects type from tag)'

inputs:
  version:
    description: 'Package version'
    required: true
  tag:
    description: 'Release tag'
    required: true
  previous-tag:
    description: 'Previous release tag for generating commit diff'
    required: false
    default: ''

outputs:
  notes-file:
    description: 'Path to generated release notes file'
    value: ${{ steps.generate.outputs.notes-file }}

runs:
  using: 'composite'
  steps:
    - name: Generate release notes
      id: generate
      shell: pwsh
      env:
        ACTION_PATH: ${{ github.action_path }}
        INPUT_VERSION: ${{ inputs.version }}
        INPUT_TAG: ${{ inputs.tag }}
        INPUT_PREVIOUS_TAG: ${{ inputs.previous-tag }}
      run: |
        & "$env:ACTION_PATH/Generate-ReleaseNotes.ps1" `
          -Version $env:INPUT_VERSION `
          -Tag $env:INPUT_TAG `
          -PreviousTag $env:INPUT_PREVIOUS_TAG
