name: 'Generate Release Notes'
description: 'Generate release notes for Momentum projects (auto-detects type from tag)'

inputs:
  version:
    description: 'Package version'
    required: true
  tag:
    description: 'Release tag'
    required: true
  previous-tag:
    description: 'Previous release tag for generating commit diff'
    required: false
    default: ''

outputs:
  notes-file:
    description: 'Path to generated release notes file'
    value: ${{ steps.generate.outputs.notes-file }}

runs:
  using: 'composite'
  steps:
    - name: Generate release notes
      id: generate
      shell: pwsh
      run: |
        & "${{ github.action_path }}/Generate-ReleaseNotes.ps1" `
          -Version "${{ inputs.version }}" `
          -Tag "${{ inputs.tag }}" `
          -PreviousTag "${{ inputs.previous-tag }}"
