// Copyright (c) Momentum .NET. All rights reserved.

using Momentum.Extensions.SourceGenerators.DbCommand;
using System.Collections.Immutable;
using System.Text;

namespace Momentum.Extensions.SourceGenerators;

/// <summary>
///     Abstract base class providing common utilities for source code generation writers.
///     Handles file headers, namespace declarations, and nested type structures.
/// </summary>
internal abstract class SourceGenBaseWriter
{
    /// <summary>
    ///     Appends opening declarations for all containing (parent) types, supporting nested type generation.
    /// </summary>
    /// <param name="sb">The StringBuilder to append to.</param>
    /// <param name="containingTypes">The hierarchy of parent types, ordered from outermost to innermost.</param>
    protected static void AppendContainingTypeStarts(StringBuilder sb, ImmutableArray<DbCommandTypeInfo.ContainingTypeInfo> containingTypes)
    {
        foreach (var type in containingTypes)
        {
            sb.AppendLine(type.TypeDeclaration);
            sb.AppendLine("{");
        }
    }

    /// <summary>
    ///     Appends closing braces for all containing (parent) types.
    /// </summary>
    /// <param name="sb">The StringBuilder to append to.</param>
    /// <param name="containingTypes">The hierarchy of parent types.</param>
    protected static void AppendContainingTypeEnds(StringBuilder sb, ImmutableArray<DbCommandTypeInfo.ContainingTypeInfo> containingTypes)
    {
        for (var i = 0; i < containingTypes.Length; i++)
        {
            sb.AppendLine("}");
        }
    }

    /// <summary>
    ///     Appends a file-scoped namespace declaration if the namespace is not null or global.
    /// </summary>
    /// <param name="sb">The StringBuilder to append to.</param>
    /// <param name="ns">The namespace name, or null for global namespace.</param>
    protected static void AppendNamespace(StringBuilder sb, string? ns)
    {
        if (ns is not null)
        {
            sb.AppendLine($"namespace {ns};");
            sb.AppendLine();
        }
    }

    /// <summary>
    ///     Appends the standard auto-generated file header with nullable enable directive.
    /// </summary>
    /// <param name="sb">The StringBuilder to append to.</param>
    protected static void AppendFileHeader(StringBuilder sb)
    {
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
    }
}
