name: "Publish NuGet Packages"
description: "Pack and publish NuGet packages"

inputs:
  path:
    description: "Path to the project or solution to pack"
    required: true
  config:
    description: "MS Build configuration"
    required: false
    default: "Release"
  package-version:
    description: "Version to use for the packages"
    required: true
  pack-args:
    description: "Additional arguments for dotnet pack"
    required: false
    default: ""
  nuget-api-key:
    description: "NuGet API key for publishing"
    required: true
  nuget-source:
    description: "NuGet source URL"
    required: false
    default: "https://api.nuget.org/v3/index.json"
  skip-duplicate:
    description: "Skip duplicate packages"
    required: false
    default: "true"
  dry-run:
    description: "Perform a dry run without actually publishing"
    required: false
    default: "false"

outputs:
  published-packages:
    description: "List of published packages"
    value: ${{ steps.publish.outputs.packages }}
  output-dir:
    description: "Packages output dir"
    value: ${{ steps.pack.outputs.output_dir }}

runs:
  using: "composite"
  steps:
    - name: Publish NuGet packages
      id: publish
      shell: pwsh
      env:
        NUGET_API_KEY: ${{ inputs.nuget-api-key }}
        INPUT_PATH: ${{ inputs.path }}
        INPUT_CONFIG: ${{ inputs.config }}
        INPUT_PACKAGE_VERSION: ${{ inputs.package-version }}
        INPUT_NUGET_SOURCE: ${{ inputs.nuget-source }}
        INPUT_PACK_ARGS: ${{ inputs.pack-args }}
        INPUT_SKIP_DUPLICATE: ${{ inputs.skip-duplicate }}
        INPUT_DRY_RUN: ${{ inputs.dry-run }}
        ACTION_PATH: ${{ github.action_path }}
      run: |
        # Mask the API key in logs
        if ($env:NUGET_API_KEY -ne "") {
          Write-Host "::add-mask::$($env:NUGET_API_KEY)"
        }

        $params = @{
          Path = $env:INPUT_PATH
          Config = $env:INPUT_CONFIG
          PackageVersion = $env:INPUT_PACKAGE_VERSION
          NugetApiKey = $env:NUGET_API_KEY
          NugetSource = $env:INPUT_NUGET_SOURCE
        }

        # Parse pack-args as an array if provided
        $packArgsInput = $env:INPUT_PACK_ARGS
        if (-not [string]::IsNullOrWhiteSpace($packArgsInput)) {
          # Split on spaces but preserve quoted strings
          $packArgsArray = $packArgsInput -split '\s+(?=(?:[^"]*"[^"]*")*[^"]*$)' | Where-Object { $_ -ne '' }
          $params['PackArgs'] = $packArgsArray
        }

        if ($env:INPUT_SKIP_DUPLICATE -eq "true") {
          $params['SkipDuplicate'] = $true
        }

        if ($env:INPUT_DRY_RUN -eq "true") {
          $params['DryRun'] = $true
        }

        & "$env:ACTION_PATH/Publish-NuGetPackages.ps1" @params
