name: "Build Documentation"
description: "Build VitePress documentation"

inputs:
  node-version:
    description: "Node.js version"
    required: false
    default: "22"
  pnpm-version:
    description: "pnpm version"
    required: false
    default: "9"
  docs-path:
    description: "Path to documentation directory"
    required: false
    default: "libs/Momentum/docs"
  build-dotnet:
    description: "Whether to build .NET projects first"
    required: false
    default: "true"

outputs:
  dist-path:
    description: "Path to built documentation"
    value: ${{ steps.paths.outputs.dist }}

runs:
  using: "composite"
  steps:
    - name: Setup pnpm
      uses: pnpm/action-setup@v4
      with:
        version: ${{ inputs.pnpm-version }}

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: pnpm
        cache-dependency-path: ${{ inputs.docs-path }}/pnpm-lock.yaml

    - name: Build .NET projects
      if: inputs.build-dotnet == 'true'
      uses: ./.github/actions/build
      with:
        build-target: libs/Momentum/Momentum.slnx

    - name: Build documentation
      id: paths
      shell: pwsh
      run: |
        & "$GITHUB_WORKSPACE/.github/scripts/Build-Documentation.ps1" `
          -NodeVersion "${{ inputs.node-version }}" `
          -PnpmVersion "${{ inputs.pnpm-version }}" `
          -DocsPath "${{ inputs.docs-path }}" `
          -BuildDotnet "${{ inputs.build-dotnet }}"

