name: "Build Documentation"
description: "Build VitePress documentation"

inputs:
  bun-version:
    description: "Bun version"
    required: false
    default: "latest"
  docs-path:
    description: "Path to documentation directory"
    required: false
    default: "libs/Momentum/docs"
  build-dotnet:
    description: "Whether to build .NET projects first"
    required: false
    default: "true"

outputs:
  dist-path:
    description: "Path to built documentation"
    value: ${{ steps.paths.outputs.dist }}

runs:
  using: "composite"
  steps:
    - name: Setup Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: ${{ inputs.bun-version }}

    - name: Build .NET projects
      if: inputs.build-dotnet == 'true'
      uses: ./.github/actions/build
      with:
        build-target: libs/Momentum/Momentum.slnx

    - name: Build documentation
      id: paths
      shell: pwsh
      run: |
        & "${{ github.action_path }}/Build-Documentation.ps1" -DocsPath "${{ inputs.docs-path }}"
