name: 'Pack Template as NuGet'
description: 'Packs the repository template (.template.config) into a NuGet template package'

inputs:
  package-id:
    description: 'NuGet package ID (e.g., Momentum.Templates)'
    required: true
  package-version:
    description: 'Package version'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Prepare artifacts dir
      shell: bash
      run: |
        mkdir -p ./artifacts/template

    - name: Create nuspec
      id: nuspec
      shell: bash
      run: |
        PKG_ID='${{ inputs.package-id }}'
        PKG_VERSION='${{ inputs.package-version }}'
        NUSPEC_PATH='./artifacts/template/template.nuspec'

        cat > "$NUSPEC_PATH" << 'EOF'
        <?xml version="1.0"?>
        <package xmlns="http://schemas.microsoft.com/packaging/2013/05/nuspec.xsd">
          <metadata>
            <id>__PKG_ID__</id>
            <version>__PKG_VERSION__</version>
            <authors>Momentum .NET</authors>
            <owners>Momentum .NET</owners>
            <requireLicenseAcceptance>false</requireLicenseAcceptance>
            <license type="expression">MIT</license>
            <projectUrl>https://github.com/vgmello/momentum</projectUrl>
            <description>Momentum .NET project template.</description>
            <packageTypes>
              <packageType name="Template" />
            </packageTypes>
            <tags>dotnet-new;template;momentum</tags>
          </metadata>
          <files>
            <!-- Include template configuration -->
            <file src=".template.config/**" target="content/" />

            <!-- Include your solution skeleton files/directories -->
            <file src="src/**" target="content/" />
            <file src="docs/**" target="content/" />
            <file src="compose.yml" target="content/" />
            <file src="README.md" target="content/" />
            <file src="ProjectREADME.md" target="content/" />
            <file src="Directory.Build.props" target="content/" />
            <file src="Directory.Packages.props" target="content/" />
            <file src="AppDomain.slnx" target="content/" />
            <file src="AppDomain.ruleset" target="content/" />

            <!-- Include libs sources in template content -->
            <file src="libs/src/**" target="content/libs/src/" />

            <!-- General include with excludes to avoid CI/dev artifacts -->
            <file src="**/*" target="content/" exclude=".git/**;**/bin/**;**/obj/**;.github/**;.idea/**;.vscode/**;tests/**;.local/**" />
          </files>
        </package>
        EOF

        # Replace placeholders
        sed -i.bak "s/__PKG_ID__/$PKG_ID/" "$NUSPEC_PATH"
        sed -i.bak "s/__PKG_VERSION__/$PKG_VERSION/" "$NUSPEC_PATH"
        rm "$NUSPEC_PATH.bak"

        echo "nuspec=$NUSPEC_PATH" >> $GITHUB_OUTPUT

    - name: Pack
      shell: bash
      run: |
        dotnet tool install --global nuget-command-line && export PATH="$PATH:$HOME/.dotnet/tools"
        nuget pack "${{ steps.nuspec.outputs.nuspec }}" -OutputDirectory ./artifacts/template -NoPackageAnalysis
        echo "📦 Packed template:"
        ls -la ./artifacts/template
