name: 'Generate Template Release Notes'
description: 'Generate release notes for Momentum template'

inputs:
  version:
    description: 'Package version'
    required: true
  tag:
    description: 'Release tag'
    required: true
  release-type:
    description: 'Type of release (prerelease/stable)'
    required: false
    default: 'stable'
  output-file:
    description: 'Output file name'
    required: false
    default: 'release_notes.md'

outputs:
  notes-file:
    description: 'Path to generated release notes file'
    value: ${{ inputs.output-file }}

runs:
  using: 'composite'
  steps:
    - name: Generate release notes
      shell: bash
      run: |
        VERSION="${{ inputs.version }}"
        TAG="${{ inputs.tag }}"
        RELEASE_TYPE="${{ inputs.release-type }}"
        OUTPUT_FILE="${{ inputs.output-file }}"

        LAST_RELEASE=$(git tag -l "t*.*.*" --sort=-v:refname | head -1)
        if [ -n "$LAST_RELEASE" ]; then
          COMMITS=$(git log --pretty=format:"- %s" ${LAST_RELEASE}..HEAD)
        else
          COMMITS=$(git log --pretty=format:"- %s")
        fi

        if [ "$RELEASE_TYPE" == "prerelease" ]; then
          cat > "$OUTPUT_FILE" << EOF
        # Momentum Template ${TAG} (Pre-release)

        🚧 **This is a pre-release version** - Use for testing purposes only

        ## Changes Since Last Template Release

        $COMMITS

        Version: ${VERSION}
        EOF
        else
          cat > "$OUTPUT_FILE" << EOF
        # Momentum Template ${TAG}

        ## Changes

        $COMMITS

        Version: ${VERSION}
        EOF
        fi

        echo "📝 Generated template release notes in $OUTPUT_FILE"
        echo "Contents:"
        cat "$OUTPUT_FILE"
