<!--#if (includeSample)-->
// Copyright (c) ABCDEG. All rights reserved.

using AppDomain.Invoices.Contracts.Models;

namespace AppDomain.Invoices.Contracts.DomainEvents;

/// <summary>
/// Domain event published when an invoice is generated within the AppDomain system. 
/// This is an internal domain event that triggers subsequent processing within the domain.
/// </summary>
/// <param name="TenantId">Unique identifier for the tenant</param>
/// <param name="Invoice">Generated invoice object</param>
/// <param name="GeneratedAt">Date and time when the invoice was generated</param>
/// <remarks>
/// ## When It's Triggered
///
/// This domain event is published when:
/// - An invoice is programmatically generated by the system
/// - Automated billing processes create new invoices
/// - Recurring invoice generation occurs
///
/// ## Domain Usage
///
/// This domain event is handled within the same domain to:
/// - Trigger additional invoice processing workflows
/// - Apply business rules specific to generated invoices
/// - Initialize invoice-specific processes
/// </remarks>
public record InvoiceGenerated(
    Guid TenantId,
    Invoice Invoice,
    DateTime GeneratedAt
);
<!--#endif-->