name: "Calculate Version"
description: "Calculate version for releases and pre-releases"

inputs:
  version-file:
    description: "Path to version file"
    required: false
    default: "version.txt"
  prerelease:
    description: "Type of release (stable/prerelease)"
    required: false
    default: "true"
  tag-prefix:
    description: "Tag prefix"
    required: false
    default: "v"

outputs:
  next-version:
    description: "Calculated version"
    value: ${{ steps.calculate.outputs.next-version }}
  next-tag:
    description: "Version tag"
    value: ${{ steps.calculate.outputs.next-tag }}
  previous-version:
    description: "Previous version"
    value: ${{ steps.calculate.outputs.previous-version }}
  previous-tag:
    description: "Previous Tag"
    value: ${{ steps.calculate.outputs.previous-tag }}
  previous-stable-version:
    description: "Previous stable version"
    value: ${{ steps.calculate.outputs.previous-stable-version }}

runs:
  using: "composite"
  steps:
    - name: Calculate version
      id: calculate
      shell: pwsh
      run: |
        & "${{ github.action_path }}/Calculate-Version.ps1" `
        -VersionFile "${{ inputs.version-file }}" `
        -Prerelease "${{ inputs.prerelease }}" `
        -TagPrefix "${{ inputs.tag-prefix }}"
