name: "Calculate Version"
description: "Calculate version for releases and pre-releases"

inputs:
  version-file:
    description: "Path to version file"
    required: false
    default: "libs/Momentum/version.txt"
  release-type:
    description: "Type of release (stable/prerelease)"
    required: false
    default: "stable"

outputs:
  version:
    description: "Calculated version"
    value: ${{ steps.calculate.outputs.version }}
  tag:
    description: "Version tag"
    value: ${{ steps.calculate.outputs.tag }}
  has-prerelease:
    description: "Whether pre-releases exist for this version"
    value: ${{ steps.calculate.outputs.has_prerelease }}
  previous-version:
    description: "Previous version"
    value: ${{ steps.calculate.outputs.previous_version }}
  previous-stable-version:
    description: "Previous version"
    value: ${{ steps.calculate.outputs.previous_stable_version }}

runs:
  using: "composite"
  steps:
    - name: Calculate version
      id: calculate
      shell: pwsh
      run: |
        & "${{ github.action_path }}/Calculate-Version.ps1" `
        -VersionFile "${{ inputs.version-file }}" `
        -ReleaseType "${{ inputs.release-type }}"
