name: "Configure Deployment"
description: "Configure deployment settings for both templates and libraries"

inputs:
  deploy-type:
    description: "Type of deployment from workflow_dispatch"
    required: false
    default: ""

outputs:
  deploy-prerelease:
    description: "Whether to deploy a prerelease (false = release)"
    value: ${{ steps.config.outputs.deploy-prerelease }}
  deploy-docs:
    description: "Whether to deploy documentation"
    value: ${{ steps.config.outputs.deploy-docs }}
  release-type:
    description: "Type of release (stable/prerelease)"
    value: ${{ steps.config.outputs.release-type }}

runs:
  using: "composite"
  steps:
    - name: Configure deployment
      id: config
      shell: pwsh
      run: |
        & "${{ github.action_path }}/Configure-Deployment.ps1" -DeployType "${{ inputs.deploy-type }}"
