name: Cleanup Claude State Branch

on:
  delete:
  pull_request:
    types: [closed]

jobs:
  cleanup:
    if: |
      (github.event_name == 'delete' && github.event.ref_type == 'branch' && startswith(github.event.ref, 'issue-')) ||
      (github.event_name == 'pull_request')
    runs-on: self-hosted
    permissions:
      contents: write
      issues: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Extract issue/PR number from deleted branch
        id: extract
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            # Handle PR merge event
            PR_NUMBER="${{ github.event.pull_request.number }}"
            DELETED_BRANCH="${{ github.event.pull_request.head.ref }}"
            echo "PR #$PR_NUMBER merged, branch: $DELETED_BRANCH"
            
            # Check if branch follows naming convention
            if [[ $DELETED_BRANCH =~ ^(issue|pr)-([0-9]+) ]]; then
              BRANCH_TYPE="${BASH_REMATCH[1]}"
              ISSUE_NUMBER="${BASH_REMATCH[2]}"
            else
              # Use PR number directly
              BRANCH_TYPE="pr"
              ISSUE_NUMBER="$PR_NUMBER"
            fi
            
            echo "BRANCH_TYPE=$BRANCH_TYPE" >> $GITHUB_OUTPUT
            echo "ISSUE_NUMBER=$ISSUE_NUMBER" >> $GITHUB_OUTPUT
            echo "DELETED_BRANCH=$DELETED_BRANCH" >> $GITHUB_OUTPUT
            echo "Found $BRANCH_TYPE number: $ISSUE_NUMBER"
          else
            # Handle branch deletion event
            DELETED_BRANCH="${{ github.event.ref }}"
            echo "Deleted branch: $DELETED_BRANCH"

            # Extract number from branch name (format: issue-{#id}-description or pr-{#id}-description or just issue-{#id} or pr-{#id})
            if [[ $DELETED_BRANCH =~ ^(issue|pr)-([0-9]+) ]]; then
              BRANCH_TYPE="${BASH_REMATCH[1]}"
              ISSUE_NUMBER="${BASH_REMATCH[2]}"
              echo "BRANCH_TYPE=$BRANCH_TYPE" >> $GITHUB_OUTPUT
              echo "ISSUE_NUMBER=$ISSUE_NUMBER" >> $GITHUB_OUTPUT
              echo "DELETED_BRANCH=$DELETED_BRANCH" >> $GITHUB_OUTPUT
              echo "Found $BRANCH_TYPE number: $ISSUE_NUMBER"
            else
              echo "Branch does not match naming convention: issue-{#id} or pr-{#id}"
              exit 0
            fi
          fi

      - name: Delete corresponding Claude state branch
        if: steps.extract.outputs.ISSUE_NUMBER
        run: |
          BRANCH_TYPE="${{ steps.extract.outputs.BRANCH_TYPE }}"
          ISSUE_NUMBER="${{ steps.extract.outputs.ISSUE_NUMBER }}"
          CLAUDE_BRANCH="claude-${BRANCH_TYPE}-${ISSUE_NUMBER}"

          echo "Looking for Claude state branch: $CLAUDE_BRANCH"

          # Check if the Claude state branch exists on remote
          if git ls-remote --heads origin "$CLAUDE_BRANCH" | grep -q "$CLAUDE_BRANCH"; then
            echo "Found Claude state branch: $CLAUDE_BRANCH"
            echo "Deleting remote branch..."
            git push origin --delete "$CLAUDE_BRANCH"
            echo "✅ Successfully deleted Claude state branch: $CLAUDE_BRANCH"
          else
            echo "ℹ️ No Claude state branch found for: $CLAUDE_BRANCH"
          fi