name: Deploy Momentum Template

on:
  push:
    branches:
      - main
    paths:
      - '.template.config/**'
      - 'src/**'
      - 'docs/**'
      - 'infra/**'
      - 'tests/**'
      - 'libs/Momentum/src/**'
      - 'libs/Momentum/Momentum.Template.csproj'
      - 'compose.yml'
      - 'README.md'
      - 'ProjectREADME.md'
      - 'Directory.Build.props'
      - 'Directory.Packages.props'
      - 'AppDomain.slnx'
      - 'AppDomain.ruleset'
      - '.gitignore'
      - '.vscode/**'
    tags:
      - 'template-v*.*.*'
  workflow_dispatch:
    inputs:
      deploy-type:
        description: 'Deployment type'
        required: true
        default: 'prerelease'
        type: choice
        options:
          - prerelease
          - release
          - test-prerelease
          - test-release

env:
  DOTNET_VERSION: '9.0.x'
  DOTNET_NOLOGO: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

concurrency:
  group: deploy-template-${{ github.ref }}
  cancel-in-progress: false

permissions:
  contents: write
  packages: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure deployment
        id: config
        uses: ./.github/actions/deployment-config
        with:
          deploy-type: ${{ github.event.inputs.deploy-type }}
          nuget-api-key: ${{ secrets.NUGET_API_KEY }}
          nuget-test-api-key: ${{ secrets.NUGET_TEST_API_KEY }}

      - name: Calculate pre-release version
        if: steps.config.outputs.deploy-prerelease == 'true'
        id: prerelease-version
        uses: ./.github/actions/version-calculate
        with:
          version-file: .template.config/version.txt
          release-type: prerelease
          check-changes: false

      - name: Generate pre-release notes
        if: steps.config.outputs.deploy-prerelease == 'true' && steps.prerelease-version.outputs.skip != 'true'
        uses: ./.github/actions/generate-release-notes
        with:
          version: ${{ steps.prerelease-version.outputs.version }}
          tag: template-${{ steps.prerelease-version.outputs.tag }}
          release-type: prerelease
          output-file: prerelease_notes.md

      - name: Create GitHub pre-release
        if: steps.config.outputs.deploy-prerelease == 'true' && steps.prerelease-version.outputs.skip != 'true' && steps.config.outputs.is-test != 'true'
        run: |
          gh release create "template-${{ steps.prerelease-version.outputs.tag }}" \
            --title "Momentum Template ${{ steps.prerelease-version.outputs.version }}" \
            --notes-file prerelease_notes.md \
            --prerelease \
            --target main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish pre-release packages
        if: steps.config.outputs.deploy-prerelease == 'true' && steps.prerelease-version.outputs.skip != 'true'
        uses: ./.github/actions/nuget-publish
        with:
          path: libs/Momentum/Momentum.Template.csproj
          package-version: ${{ steps.prerelease-version.outputs.version }}
          pack-args: -p:PackTemplate=true --restore
          nuget-api-key: ${{ steps.config.outputs.nuget-api-key }}
          nuget-source: ${{ steps.config.outputs.nuget-source }}

      - name: Verify main branch for release
        if: steps.config.outputs.deploy-prerelease == 'false'
        run: |
          CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
          if [ "$CURRENT_BRANCH" != "main" ]; then
            echo "❌ Release must be created from main branch. Current: $CURRENT_BRANCH"
            exit 1
          fi
          echo "✅ Confirmed on main branch"

      - name: Calculate release version
        if: steps.config.outputs.deploy-prerelease == 'false'
        id: release-version
        uses: ./.github/actions/version-calculate
        with:
          version-file: .template.config/version.txt
          release-type: stable
          check-changes: false

      - name: Generate release notes
        if: steps.config.outputs.deploy-prerelease == 'false'
        uses: ./.github/actions/generate-release-notes
        with:
          version: ${{ steps.release-version.outputs.version }}
          tag: template-${{ steps.release-version.outputs.tag }}
          release-type: stable
          output-file: release_notes.md

      - name: Create GitHub release
        if: steps.config.outputs.deploy-prerelease == 'false' && steps.config.outputs.is-test != 'true'
        run: |
          gh release create "template-${{ steps.release-version.outputs.tag }}" \
            --title "Momentum Template v${{ steps.release-version.outputs.version }}" \
            --notes-file release_notes.md \
            --target main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish release packages
        if: steps.config.outputs.deploy-prerelease == 'false'
        uses: ./.github/actions/nuget-publish
        with:
          path: libs/Momentum/Momentum.Template.csproj
          package-version: ${{ steps.release-version.outputs.version }}
          pack-args: -p:PackTemplate=true --restore
          nuget-api-key: ${{ steps.config.outputs.nuget-api-key }}
          nuget-source: ${{ steps.config.outputs.nuget-source }}

      - name: Update version file
        if: steps.config.outputs.deploy-prerelease == 'false' && steps.config.outputs.is-test != 'true'
        shell: bash
        run: |
          # Increment patch version for next development cycle
          IFS='.' read -ra VERSION_PARTS <<< "${{ steps.release-version.outputs.version }}"
          MAJOR="${VERSION_PARTS[0]}"
          MINOR="${VERSION_PARTS[1]}"
          PATCH="${VERSION_PARTS[2]}"
          NEXT_PATCH=$((PATCH + 1))
          NEXT_VERSION="${MAJOR}.${MINOR}.${NEXT_PATCH}"

          echo "$NEXT_VERSION" > .template.config/version.txt

          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .template.config/version.txt
          git commit -m "chore: bump template version to $NEXT_VERSION [skip ci]"
          git push

      - name: Deployment Summary
        run: |
          echo "# 📊 Deployment Summary"
          echo ""

          if [ "${{ steps.config.outputs.is-test }}" == "true" ]; then
            echo "🧪 **Test Deployment Mode**"
            echo "   - NuGet Source: ${{ steps.config.outputs.nuget-source }}"
            echo ""
          fi

          if [ "${{ steps.config.outputs.deploy-prerelease }}" == "true" ]; then
            if [ "${{ steps.prerelease-version.outputs.skip }}" == "true" ]; then
              echo "⏭️ Pre-release skipped (no consumer-visible changes)"
            elif [ -n "${{ steps.prerelease-version.outputs.version }}" ]; then
              echo "✅ **Pre-release deployed**"
              echo "   - Version: ${{ steps.prerelease-version.outputs.version }}"
              echo "   - Tag: template-${{ steps.prerelease-version.outputs.tag }}"
              echo "   - NuGet: ${{ steps.config.outputs.nuget-source }}"
              if [ "${{ steps.config.outputs.is-test }}" != "true" ]; then
                echo "   - GitHub Release: Created"
              fi
            else
              echo "❌ **Pre-release failed**"
            fi
          fi

          if [ "${{ steps.config.outputs.deploy-prerelease }}" == "false" ]; then
            if [ -n "${{ steps.release-version.outputs.version }}" ]; then
              echo "✅ **Release deployed**"
              echo "   - Version: ${{ steps.release-version.outputs.version }}"
              echo "   - Tag: template-${{ steps.release-version.outputs.tag }}"
              echo "   - NuGet: ${{ steps.config.outputs.nuget-source }}"
              if [ "${{ steps.config.outputs.is-test }}" != "true" ]; then
                echo "   - GitHub Release: Created"
              fi
            else
              echo "❌ **Release failed**"
            fi
          fi
